### ISSUE TITLE
hi,can you share your pretrained weights? i can not find vit_large_p16_384_20220308-d4efb41d.pth, thanks

### ISSUE THREAD

**Issue by ChunyanWang1** [zbwxp/SegVit#1]

**Comment by AkideLiu** [comment]
Did a quick search on mmseg codebase, this config contains the vit checkpoints https://github.com/open-mmlab/mmsegmentation/blob/master/configs/segmenter/segmenter_vit-l_mask_8x1_640x640_160k_ade20k.py

checkpoint = 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segmenter/vit_large_p16_384_20220308-d4efb41d.pth'  # noqa

**Comment by ChunyanWang1** [comment]
thank you so much
