### ISSUE TITLE
use checkpointing to save memory

### ISSUE THREAD

**Issue by ydhongHIT** [zbwxp/SegVit#10]
Did you try checkpointing? It will cause the error: Expected to mark a variable ready only once. Without checkpointing, I can't even train the large model with 8 RTX3090.

**Comment by AkideLiu** [comment]
We have not try gradinet checkpoint yet, but we might look into optimization by memory effective attend in Facebook xformers.

**Comment by ydhongHIT** [comment]
> We have not tired gradinet checkpoint yet, but we might look into optimization by memory effective attention in Facebook xformers.

Thanks for the reply. By the way, is segvit v2 a new, improved method?

**Comment by AkideLiu** [comment]
> > We have not tired gradinet checkpoint yet, but we might look into optimization by memory effective attention in Facebook xformers.
> 
> Thanks for the reply. By the way, is segvit v2 a new, improved method?

Yes, it will be an extended and stronger version based on the current SegViT.
