### ISSUE TITLE
Doubt About the Paper: Segmentation Mask

### ISSUE THREAD

**Issue by Marcelo5444** [zbwxp/SegVit#4]
If the Decoder has 8 heads (at it is stated in the config) how do you convert this to NxL? which is later reshaped the the segmentation mask. If you have 8 heads, We will have 8 posible masks right?

**Comment by zbwxp** [comment]
No, sum the heads along the heads

**Comment by Marcelo5444** [comment]
Do all heads process all the tokens, or each heads takes an split of tokens? 

Thanks!

**Comment by zbwxp** [comment]
in /decode_heads/atm_head.py line 113
```
        attn_save = attn.clone()
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, Nq, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x.transpose(0, 1), attn_save.sum(dim=1) / self.num_heads
```

Thus, out is one mask

`Do all heads process all the tokens, or each heads takes an split of tokens?'
If I understand you correctly: 
class embeddings are (150, 384) for ade20k 150 classes
one decoder process all tokens (e.g. 150 tokens for ade20k).  
heads are processing the dimension of cls token channels (e.g. 384 ch）
