### ISSUE TITLE
Would you like to provide the pretrained weights?

### ISSUE THREAD

**Issue by 1787648106** [zbwxp/SegVit#7]
Thank you for your outstanding work. Would you like to share the models pretrained weights to me. Thanks a lot.

**Comment by AkideLiu** [comment]
We have updated the pre-trained backbone to https source for an easy download, and the checkpoint link shows below for reference :

checkpoint = 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segmenter/vit_large_p16_384_20220308-d4efb41d.pth'

**Comment by 1787648106** [comment]
Oh, It's my fault to bother you again, Could you tell me how long did you train on the pascal-context dataset using the vit(not shrink version)? And what's your hardware environment. Thank you again!

**Comment by AkideLiu** [comment]
We trained for around 8 hours for SegViT Large for the Pascal-context dataset with a node of 4 A100.

**Comment by 1787648106** [comment]
Thank you very much for your reply. Wishing you success in your research.

**Comment by 1787648106** [comment]
> We trained for around 8 hours for SegViT Large for the Pascal-context dataset with a node of 4 A100.
Hi, I have a naive question, is the pacscal context configuration defaulted to 60 categories? If I want to change the pascal context to include 59 classes, it is model=[...decode_head=dict(...num_classes=59...) in configs/segvit/segvit...480..80k_pc.py ..] and loss_decode=dict(...num_classes=59...)? Thanks again!
![QQ图片20230513144906](https://github.com/zbwxp/SegVit/assets/22196901/0e2e9f90-b2a1-4f12-8ef3-7214ad929308)
